// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_REQUEST_TYPE_UNSPECIFIED         RequestType = 0
	RequestType_REQUEST_TYPE_REGISTER            RequestType = 1
	RequestType_REQUEST_TYPE_HEARTBEAT           RequestType = 2
	RequestType_REQUEST_TYPE_STAGE_RUN_MESSAGE   RequestType = 3
	RequestType_REQUEST_TYPE_SUBSCRIBE           RequestType = 4
	RequestType_REQUEST_TYPE_HANDLE_STAGE_START  RequestType = 5
	RequestType_REQUEST_TYPE_HANDLE_STAGE_FINISH RequestType = 6
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REQUEST_TYPE_UNSPECIFIED",
		1: "REQUEST_TYPE_REGISTER",
		2: "REQUEST_TYPE_HEARTBEAT",
		3: "REQUEST_TYPE_STAGE_RUN_MESSAGE",
		4: "REQUEST_TYPE_SUBSCRIBE",
		5: "REQUEST_TYPE_HANDLE_STAGE_START",
		6: "REQUEST_TYPE_HANDLE_STAGE_FINISH",
	}
	RequestType_value = map[string]int32{
		"REQUEST_TYPE_UNSPECIFIED":         0,
		"REQUEST_TYPE_REGISTER":            1,
		"REQUEST_TYPE_HEARTBEAT":           2,
		"REQUEST_TYPE_STAGE_RUN_MESSAGE":   3,
		"REQUEST_TYPE_SUBSCRIBE":           4,
		"REQUEST_TYPE_HANDLE_STAGE_START":  5,
		"REQUEST_TYPE_HANDLE_STAGE_FINISH": 6,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

type ResponseType int32

const (
	ResponseType_RESPONSE_TYPE_REGISTER          ResponseType = 0
	ResponseType_RESPONSE_TYPE_HEARTBEAT         ResponseType = 1
	ResponseType_RESPONSE_TYPE_STAGE_RUN_MESSAGE ResponseType = 2
	ResponseType_RESPONSE_TYPE_WORK_ITEM         ResponseType = 3
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "RESPONSE_TYPE_REGISTER",
		1: "RESPONSE_TYPE_HEARTBEAT",
		2: "RESPONSE_TYPE_STAGE_RUN_MESSAGE",
		3: "RESPONSE_TYPE_WORK_ITEM",
	}
	ResponseType_value = map[string]int32{
		"RESPONSE_TYPE_REGISTER":          0,
		"RESPONSE_TYPE_HEARTBEAT":         1,
		"RESPONSE_TYPE_STAGE_RUN_MESSAGE": 2,
		"RESPONSE_TYPE_WORK_ITEM":         3,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_proto_enumTypes[1].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_proto_agent_proto_enumTypes[1]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

type AgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  RequestType            `protobuf:"varint,1,opt,name=type,proto3,enum=agent.RequestType" json:"type,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentRequest_Register
	//	*AgentRequest_Heartbeat
	//	*AgentRequest_StageRunMessage
	//	*AgentRequest_Subscribe
	//	*AgentRequest_HandleStageStart
	//	*AgentRequest_HandleStageFinish
	Body          isAgentRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_REQUEST_TYPE_UNSPECIFIED
}

func (x *AgentRequest) GetBody() isAgentRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentRequest) GetRegister() *RegisterBody {
	if x != nil {
		if x, ok := x.Body.(*AgentRequest_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentRequest) GetHeartbeat() *HeartbeatBody {
	if x != nil {
		if x, ok := x.Body.(*AgentRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentRequest) GetStageRunMessage() *StageRunMessageBody {
	if x != nil {
		if x, ok := x.Body.(*AgentRequest_StageRunMessage); ok {
			return x.StageRunMessage
		}
	}
	return nil
}

func (x *AgentRequest) GetSubscribe() *SubscribeBody {
	if x != nil {
		if x, ok := x.Body.(*AgentRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *AgentRequest) GetHandleStageStart() *HandleStageStartBody {
	if x != nil {
		if x, ok := x.Body.(*AgentRequest_HandleStageStart); ok {
			return x.HandleStageStart
		}
	}
	return nil
}

func (x *AgentRequest) GetHandleStageFinish() *HandleStageFinishBody {
	if x != nil {
		if x, ok := x.Body.(*AgentRequest_HandleStageFinish); ok {
			return x.HandleStageFinish
		}
	}
	return nil
}

type isAgentRequest_Body interface {
	isAgentRequest_Body()
}

type AgentRequest_Register struct {
	Register *RegisterBody `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type AgentRequest_Heartbeat struct {
	Heartbeat *HeartbeatBody `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentRequest_StageRunMessage struct {
	StageRunMessage *StageRunMessageBody `protobuf:"bytes,4,opt,name=stage_run_message,json=stageRunMessage,proto3,oneof"`
}

type AgentRequest_Subscribe struct {
	Subscribe *SubscribeBody `protobuf:"bytes,5,opt,name=subscribe,proto3,oneof"`
}

type AgentRequest_HandleStageStart struct {
	HandleStageStart *HandleStageStartBody `protobuf:"bytes,6,opt,name=handle_stage_start,json=handleStageStart,proto3,oneof"`
}

type AgentRequest_HandleStageFinish struct {
	HandleStageFinish *HandleStageFinishBody `protobuf:"bytes,7,opt,name=handle_stage_finish,json=handleStageFinish,proto3,oneof"`
}

func (*AgentRequest_Register) isAgentRequest_Body() {}

func (*AgentRequest_Heartbeat) isAgentRequest_Body() {}

func (*AgentRequest_StageRunMessage) isAgentRequest_Body() {}

func (*AgentRequest_Subscribe) isAgentRequest_Body() {}

func (*AgentRequest_HandleStageStart) isAgentRequest_Body() {}

func (*AgentRequest_HandleStageFinish) isAgentRequest_Body() {}

type RegisterBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBody) Reset() {
	*x = RegisterBody{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBody) ProtoMessage() {}

func (x *RegisterBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBody.ProtoReflect.Descriptor instead.
func (*RegisterBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterBody) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *RegisterBody) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatBody) Reset() {
	*x = HeartbeatBody{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatBody) ProtoMessage() {}

func (x *HeartbeatBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatBody.ProtoReflect.Descriptor instead.
func (*HeartbeatBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatBody) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatBody) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StageRunMessageBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	StageRunId    string                 `protobuf:"bytes,2,opt,name=stage_run_id,json=stageRunId,proto3" json:"stage_run_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageRunMessageBody) Reset() {
	*x = StageRunMessageBody{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageRunMessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageRunMessageBody) ProtoMessage() {}

func (x *StageRunMessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageRunMessageBody.ProtoReflect.Descriptor instead.
func (*StageRunMessageBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StageRunMessageBody) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *StageRunMessageBody) GetStageRunId() string {
	if x != nil {
		return x.StageRunId
	}
	return ""
}

func (x *StageRunMessageBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StageRunMessageBody) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type HandleStageStartBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	StageRunId    string                 `protobuf:"bytes,2,opt,name=stage_run_id,json=stageRunId,proto3" json:"stage_run_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleStageStartBody) Reset() {
	*x = HandleStageStartBody{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleStageStartBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleStageStartBody) ProtoMessage() {}

func (x *HandleStageStartBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleStageStartBody.ProtoReflect.Descriptor instead.
func (*HandleStageStartBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HandleStageStartBody) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HandleStageStartBody) GetStageRunId() string {
	if x != nil {
		return x.StageRunId
	}
	return ""
}

func (x *HandleStageStartBody) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HandleStageFinishBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageRunId    string                 `protobuf:"bytes,1,opt,name=stage_run_id,json=stageRunId,proto3" json:"stage_run_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Outputs       map[string]string      `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleStageFinishBody) Reset() {
	*x = HandleStageFinishBody{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleStageFinishBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleStageFinishBody) ProtoMessage() {}

func (x *HandleStageFinishBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleStageFinishBody.ProtoReflect.Descriptor instead.
func (*HandleStageFinishBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HandleStageFinishBody) GetStageRunId() string {
	if x != nil {
		return x.StageRunId
	}
	return ""
}

func (x *HandleStageFinishBody) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleStageFinishBody) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandleStageFinishBody) GetOutputs() map[string]string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type SubscribeBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBody) Reset() {
	*x = SubscribeBody{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBody) ProtoMessage() {}

func (x *SubscribeBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBody.ProtoReflect.Descriptor instead.
func (*SubscribeBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeBody) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type AgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ResponseType           `protobuf:"varint,1,opt,name=type,proto3,enum=agent.ResponseType" json:"type,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentResponse_Register
	//	*AgentResponse_Heartbeat
	//	*AgentResponse_StageRunMessage
	//	*AgentResponse_WorkItem
	Body          isAgentResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResponse) Reset() {
	*x = AgentResponse{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResponse) ProtoMessage() {}

func (x *AgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResponse.ProtoReflect.Descriptor instead.
func (*AgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_RESPONSE_TYPE_REGISTER
}

func (x *AgentResponse) GetBody() isAgentResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentResponse) GetRegister() *RegisterResponseBody {
	if x != nil {
		if x, ok := x.Body.(*AgentResponse_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentResponse) GetHeartbeat() *HeartbeatResponseBody {
	if x != nil {
		if x, ok := x.Body.(*AgentResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentResponse) GetStageRunMessage() *StageRunMessageResponseBody {
	if x != nil {
		if x, ok := x.Body.(*AgentResponse_StageRunMessage); ok {
			return x.StageRunMessage
		}
	}
	return nil
}

func (x *AgentResponse) GetWorkItem() *WorkItemBody {
	if x != nil {
		if x, ok := x.Body.(*AgentResponse_WorkItem); ok {
			return x.WorkItem
		}
	}
	return nil
}

type isAgentResponse_Body interface {
	isAgentResponse_Body()
}

type AgentResponse_Register struct {
	Register *RegisterResponseBody `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

type AgentResponse_Heartbeat struct {
	Heartbeat *HeartbeatResponseBody `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type AgentResponse_StageRunMessage struct {
	StageRunMessage *StageRunMessageResponseBody `protobuf:"bytes,4,opt,name=stage_run_message,json=stageRunMessage,proto3,oneof"`
}

type AgentResponse_WorkItem struct {
	WorkItem *WorkItemBody `protobuf:"bytes,5,opt,name=work_item,json=workItem,proto3,oneof"`
}

func (*AgentResponse_Register) isAgentResponse_Body() {}

func (*AgentResponse_Heartbeat) isAgentResponse_Body() {}

func (*AgentResponse_StageRunMessage) isAgentResponse_Body() {}

func (*AgentResponse_WorkItem) isAgentResponse_Body() {}

type RegisterResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponseBody) Reset() {
	*x = RegisterResponseBody{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponseBody) ProtoMessage() {}

func (x *RegisterResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponseBody.ProtoReflect.Descriptor instead.
func (*RegisterResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterResponseBody) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponseBody) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterResponseBody) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatResponseBody struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AssignedWorkerId string                 `protobuf:"bytes,2,opt,name=assigned_worker_id,json=assignedWorkerId,proto3" json:"assigned_worker_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponseBody) Reset() {
	*x = HeartbeatResponseBody{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponseBody) ProtoMessage() {}

func (x *HeartbeatResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponseBody.ProtoReflect.Descriptor instead.
func (*HeartbeatResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponseBody) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponseBody) GetAssignedWorkerId() string {
	if x != nil {
		return x.AssignedWorkerId
	}
	return ""
}

type StageRunMessageResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageRunMessageResponseBody) Reset() {
	*x = StageRunMessageResponseBody{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageRunMessageResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageRunMessageResponseBody) ProtoMessage() {}

func (x *StageRunMessageResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageRunMessageResponseBody.ProtoReflect.Descriptor instead.
func (*StageRunMessageResponseBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *StageRunMessageResponseBody) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WorkItemBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	StageRunId    string                 `protobuf:"bytes,2,opt,name=stage_run_id,json=stageRunId,proto3" json:"stage_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItemBody) Reset() {
	*x = WorkItemBody{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItemBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItemBody) ProtoMessage() {}

func (x *WorkItemBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItemBody.ProtoReflect.Descriptor instead.
func (*WorkItemBody) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *WorkItemBody) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *WorkItemBody) GetStageRunId() string {
	if x != nil {
		return x.StageRunId
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"\xc4\x03\n" +
	"\fAgentRequest\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.agent.RequestTypeR\x04type\x121\n" +
	"\bregister\x18\x02 \x01(\v2\x13.agent.RegisterBodyH\x00R\bregister\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.agent.HeartbeatBodyH\x00R\theartbeat\x12H\n" +
	"\x11stage_run_message\x18\x04 \x01(\v2\x1a.agent.StageRunMessageBodyH\x00R\x0fstageRunMessage\x124\n" +
	"\tsubscribe\x18\x05 \x01(\v2\x14.agent.SubscribeBodyH\x00R\tsubscribe\x12K\n" +
	"\x12handle_stage_start\x18\x06 \x01(\v2\x1b.agent.HandleStageStartBodyH\x00R\x10handleStageStart\x12N\n" +
	"\x13handle_stage_finish\x18\a \x01(\v2\x1c.agent.HandleStageFinishBodyH\x00R\x11handleStageFinishB\x06\n" +
	"\x04body\"@\n" +
	"\fRegisterBody\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"D\n" +
	"\rHeartbeatBody\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x84\x01\n" +
	"\x13StageRunMessageBody\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12 \n" +
	"\fstage_run_id\x18\x02 \x01(\tR\n" +
	"stageRunId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\"o\n" +
	"\x14HandleStageStartBody\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12 \n" +
	"\fstage_run_id\x18\x02 \x01(\tR\n" +
	"stageRunId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xe8\x01\n" +
	"\x15HandleStageFinishBody\x12 \n" +
	"\fstage_run_id\x18\x01 \x01(\tR\n" +
	"stageRunId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12C\n" +
	"\aoutputs\x18\x04 \x03(\v2).agent.HandleStageFinishBody.OutputsEntryR\aoutputs\x1a:\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\rSubscribeBody\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xbf\x02\n" +
	"\rAgentResponse\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.agent.ResponseTypeR\x04type\x129\n" +
	"\bregister\x18\x02 \x01(\v2\x1b.agent.RegisterResponseBodyH\x00R\bregister\x12<\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1c.agent.HeartbeatResponseBodyH\x00R\theartbeat\x12P\n" +
	"\x11stage_run_message\x18\x04 \x01(\v2\".agent.StageRunMessageResponseBodyH\x00R\x0fstageRunMessage\x122\n" +
	"\twork_item\x18\x05 \x01(\v2\x13.agent.WorkItemBodyH\x00R\bworkItemB\x06\n" +
	"\x04body\"c\n" +
	"\x14RegisterResponseBody\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"_\n" +
	"\x15HeartbeatResponseBody\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x12assigned_worker_id\x18\x02 \x01(\tR\x10assignedWorkerId\"7\n" +
	"\x1bStageRunMessageResponseBody\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\fWorkItemBody\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12 \n" +
	"\fstage_run_id\x18\x02 \x01(\tR\n" +
	"stageRunId*\xed\x01\n" +
	"\vRequestType\x12\x1c\n" +
	"\x18REQUEST_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REQUEST_TYPE_REGISTER\x10\x01\x12\x1a\n" +
	"\x16REQUEST_TYPE_HEARTBEAT\x10\x02\x12\"\n" +
	"\x1eREQUEST_TYPE_STAGE_RUN_MESSAGE\x10\x03\x12\x1a\n" +
	"\x16REQUEST_TYPE_SUBSCRIBE\x10\x04\x12#\n" +
	"\x1fREQUEST_TYPE_HANDLE_STAGE_START\x10\x05\x12$\n" +
	" REQUEST_TYPE_HANDLE_STAGE_FINISH\x10\x06*\x89\x01\n" +
	"\fResponseType\x12\x1a\n" +
	"\x16RESPONSE_TYPE_REGISTER\x10\x00\x12\x1b\n" +
	"\x17RESPONSE_TYPE_HEARTBEAT\x10\x01\x12#\n" +
	"\x1fRESPONSE_TYPE_STAGE_RUN_MESSAGE\x10\x02\x12\x1b\n" +
	"\x17RESPONSE_TYPE_WORK_ITEM\x10\x032J\n" +
	"\fAgentService\x12:\n" +
	"\tSubscribe\x12\x13.agent.AgentRequest\x1a\x14.agent.AgentResponse(\x010\x01B\x1cZ\x1atorv.io/worker-agent/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_agent_proto_goTypes = []any{
	(RequestType)(0),                    // 0: agent.RequestType
	(ResponseType)(0),                   // 1: agent.ResponseType
	(*AgentRequest)(nil),                // 2: agent.AgentRequest
	(*RegisterBody)(nil),                // 3: agent.RegisterBody
	(*HeartbeatBody)(nil),               // 4: agent.HeartbeatBody
	(*StageRunMessageBody)(nil),         // 5: agent.StageRunMessageBody
	(*HandleStageStartBody)(nil),        // 6: agent.HandleStageStartBody
	(*HandleStageFinishBody)(nil),       // 7: agent.HandleStageFinishBody
	(*SubscribeBody)(nil),               // 8: agent.SubscribeBody
	(*AgentResponse)(nil),               // 9: agent.AgentResponse
	(*RegisterResponseBody)(nil),        // 10: agent.RegisterResponseBody
	(*HeartbeatResponseBody)(nil),       // 11: agent.HeartbeatResponseBody
	(*StageRunMessageResponseBody)(nil), // 12: agent.StageRunMessageResponseBody
	(*WorkItemBody)(nil),                // 13: agent.WorkItemBody
	nil,                                 // 14: agent.HandleStageFinishBody.OutputsEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	0,  // 0: agent.AgentRequest.type:type_name -> agent.RequestType
	3,  // 1: agent.AgentRequest.register:type_name -> agent.RegisterBody
	4,  // 2: agent.AgentRequest.heartbeat:type_name -> agent.HeartbeatBody
	5,  // 3: agent.AgentRequest.stage_run_message:type_name -> agent.StageRunMessageBody
	8,  // 4: agent.AgentRequest.subscribe:type_name -> agent.SubscribeBody
	6,  // 5: agent.AgentRequest.handle_stage_start:type_name -> agent.HandleStageStartBody
	7,  // 6: agent.AgentRequest.handle_stage_finish:type_name -> agent.HandleStageFinishBody
	14, // 7: agent.HandleStageFinishBody.outputs:type_name -> agent.HandleStageFinishBody.OutputsEntry
	1,  // 8: agent.AgentResponse.type:type_name -> agent.ResponseType
	10, // 9: agent.AgentResponse.register:type_name -> agent.RegisterResponseBody
	11, // 10: agent.AgentResponse.heartbeat:type_name -> agent.HeartbeatResponseBody
	12, // 11: agent.AgentResponse.stage_run_message:type_name -> agent.StageRunMessageResponseBody
	13, // 12: agent.AgentResponse.work_item:type_name -> agent.WorkItemBody
	2,  // 13: agent.AgentService.Subscribe:input_type -> agent.AgentRequest
	9,  // 14: agent.AgentService.Subscribe:output_type -> agent.AgentResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentRequest_Register)(nil),
		(*AgentRequest_Heartbeat)(nil),
		(*AgentRequest_StageRunMessage)(nil),
		(*AgentRequest_Subscribe)(nil),
		(*AgentRequest_HandleStageStart)(nil),
		(*AgentRequest_HandleStageFinish)(nil),
	}
	file_proto_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*AgentResponse_Register)(nil),
		(*AgentResponse_Heartbeat)(nil),
		(*AgentResponse_StageRunMessage)(nil),
		(*AgentResponse_WorkItem)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
