// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ── worker → orchestrator ──
type WorkerMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	WorkerId string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Types that are valid to be assigned to Type:
	//
	//	*WorkerMessage_Session
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_Log
	//	*WorkerMessage_Result
	Type          isWorkerMessage_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerMessage) GetType() isWorkerMessage_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *WorkerMessage) GetSession() *Session {
	if x != nil {
		if x, ok := x.Type.(*WorkerMessage_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Type.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetLog() *RunLog {
	if x != nil {
		if x, ok := x.Type.(*WorkerMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *RunResult {
	if x != nil {
		if x, ok := x.Type.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isWorkerMessage_Type interface {
	isWorkerMessage_Type()
}

type WorkerMessage_Session struct {
	Session *Session `protobuf:"bytes,2,opt,name=session,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_Log struct {
	Log *RunLog `protobuf:"bytes,5,opt,name=log,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *RunResult `protobuf:"bytes,6,opt,name=result,proto3,oneof"`
}

func (*WorkerMessage_Session) isWorkerMessage_Type() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Type() {}

func (*WorkerMessage_Log) isWorkerMessage_Type() {}

func (*WorkerMessage_Result) isWorkerMessage_Type() {}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RunLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLog) Reset() {
	*x = RunLog{}
	mi := &file_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLog) ProtoMessage() {}

func (x *RunLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLog.ProtoReflect.Descriptor instead.
func (*RunLog) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *RunLog) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *RunLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	OutputsJson   *string                `protobuf:"bytes,5,opt,name=outputs_json,json=outputsJson,proto3,oneof" json:"outputs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResult) Reset() {
	*x = RunResult{}
	mi := &file_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResult) ProtoMessage() {}

func (x *RunResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResult.ProtoReflect.Descriptor instead.
func (*RunResult) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *RunResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RunResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *RunResult) GetOutputsJson() string {
	if x != nil && x.OutputsJson != nil {
		return *x.OutputsJson
	}
	return ""
}

// ── orchestrator → worker ──
type OrchestratorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*OrchestratorMessage_Session
	//	*OrchestratorMessage_Dispatch
	//	*OrchestratorMessage_Abort
	Body          isOrchestratorMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrchestratorMessage) Reset() {
	*x = OrchestratorMessage{}
	mi := &file_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrchestratorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrchestratorMessage) ProtoMessage() {}

func (x *OrchestratorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrchestratorMessage.ProtoReflect.Descriptor instead.
func (*OrchestratorMessage) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *OrchestratorMessage) GetBody() isOrchestratorMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OrchestratorMessage) GetSession() *SessionReady {
	if x != nil {
		if x, ok := x.Body.(*OrchestratorMessage_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetDispatch() *RunDispatch {
	if x != nil {
		if x, ok := x.Body.(*OrchestratorMessage_Dispatch); ok {
			return x.Dispatch
		}
	}
	return nil
}

func (x *OrchestratorMessage) GetAbort() *RunAbort {
	if x != nil {
		if x, ok := x.Body.(*OrchestratorMessage_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

type isOrchestratorMessage_Body interface {
	isOrchestratorMessage_Body()
}

type OrchestratorMessage_Session struct {
	Session *SessionReady `protobuf:"bytes,1,opt,name=session,proto3,oneof"`
}

type OrchestratorMessage_Dispatch struct {
	Dispatch *RunDispatch `protobuf:"bytes,2,opt,name=dispatch,proto3,oneof"`
}

type OrchestratorMessage_Abort struct {
	Abort *RunAbort `protobuf:"bytes,3,opt,name=abort,proto3,oneof"`
}

func (*OrchestratorMessage_Session) isOrchestratorMessage_Body() {}

func (*OrchestratorMessage_Dispatch) isOrchestratorMessage_Body() {}

func (*OrchestratorMessage_Abort) isOrchestratorMessage_Body() {}

type SessionReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReady) Reset() {
	*x = SessionReady{}
	mi := &file_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReady) ProtoMessage() {}

func (x *SessionReady) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReady.ProtoReflect.Descriptor instead.
func (*SessionReady) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *SessionReady) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SessionReady) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RunDispatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StageId       string                 `protobuf:"bytes,2,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	RunnerId      string                 `protobuf:"bytes,3,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	RunnerType    string                 `protobuf:"bytes,4,opt,name=runner_type,json=runnerType,proto3" json:"runner_type,omitempty"`
	CodeUrl       string                 `protobuf:"bytes,5,opt,name=code_url,json=codeUrl,proto3" json:"code_url,omitempty"`
	ConfigUrl     string                 `protobuf:"bytes,6,opt,name=config_url,json=configUrl,proto3" json:"config_url,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,7,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	InputsUrl     string                 `protobuf:"bytes,8,opt,name=inputs_url,json=inputsUrl,proto3" json:"inputs_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunDispatch) Reset() {
	*x = RunDispatch{}
	mi := &file_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDispatch) ProtoMessage() {}

func (x *RunDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDispatch.ProtoReflect.Descriptor instead.
func (*RunDispatch) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *RunDispatch) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunDispatch) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *RunDispatch) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RunDispatch) GetRunnerType() string {
	if x != nil {
		return x.RunnerType
	}
	return ""
}

func (x *RunDispatch) GetCodeUrl() string {
	if x != nil {
		return x.CodeUrl
	}
	return ""
}

func (x *RunDispatch) GetConfigUrl() string {
	if x != nil {
		return x.ConfigUrl
	}
	return ""
}

func (x *RunDispatch) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *RunDispatch) GetInputsUrl() string {
	if x != nil {
		return x.InputsUrl
	}
	return ""
}

type RunAbort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAbort) Reset() {
	*x = RunAbort{}
	mi := &file_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAbort) ProtoMessage() {}

func (x *RunAbort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAbort.ProtoReflect.Descriptor instead.
func (*RunAbort) Descriptor() ([]byte, []int) {
	return file_proto_worker_proto_rawDescGZIP(), []int{8}
}

func (x *RunAbort) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunAbort) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_worker_proto protoreflect.FileDescriptor

const file_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/worker.proto\x12\x06worker\"\xe5\x01\n" +
	"\rWorkerMessage\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12+\n" +
	"\asession\x18\x02 \x01(\v2\x0f.worker.SessionH\x00R\asession\x121\n" +
	"\theartbeat\x18\x03 \x01(\v2\x11.worker.HeartbeatH\x00R\theartbeat\x12\"\n" +
	"\x03log\x18\x05 \x01(\v2\x0e.worker.RunLogH\x00R\x03log\x12+\n" +
	"\x06result\x18\x06 \x01(\v2\x11.worker.RunResultH\x00R\x06resultB\x06\n" +
	"\x04type\"B\n" +
	"\aSession\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"#\n" +
	"\tHeartbeat\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"O\n" +
	"\x06RunLog\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xac\x01\n" +
	"\tRunResult\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01\x12&\n" +
	"\foutputs_json\x18\x05 \x01(\tH\x01R\voutputsJson\x88\x01\x01B\b\n" +
	"\x06_errorB\x0f\n" +
	"\r_outputs_json\"\xac\x01\n" +
	"\x13OrchestratorMessage\x120\n" +
	"\asession\x18\x01 \x01(\v2\x14.worker.SessionReadyH\x00R\asession\x121\n" +
	"\bdispatch\x18\x02 \x01(\v2\x13.worker.RunDispatchH\x00R\bdispatch\x12(\n" +
	"\x05abort\x18\x03 \x01(\v2\x10.worker.RunAbortH\x00R\x05abortB\x06\n" +
	"\x04body\"A\n" +
	"\fSessionReady\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf7\x01\n" +
	"\vRunDispatch\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bstage_id\x18\x02 \x01(\tR\astageId\x12\x1b\n" +
	"\trunner_id\x18\x03 \x01(\tR\brunnerId\x12\x1f\n" +
	"\vrunner_type\x18\x04 \x01(\tR\n" +
	"runnerType\x12\x19\n" +
	"\bcode_url\x18\x05 \x01(\tR\acodeUrl\x12\x1d\n" +
	"\n" +
	"config_url\x18\x06 \x01(\tR\tconfigUrl\x12\x1f\n" +
	"\vparams_json\x18\a \x01(\tR\n" +
	"paramsJson\x12\x1d\n" +
	"\n" +
	"inputs_url\x18\b \x01(\tR\tinputsUrl\"9\n" +
	"\bRunAbort\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2T\n" +
	"\rWorkerService\x12C\n" +
	"\tSubscribe\x12\x15.worker.WorkerMessage\x1a\x1b.worker.OrchestratorMessage(\x010\x01B\x1cZ\x1atorv.io/worker-agent/protob\x06proto3"

var (
	file_proto_worker_proto_rawDescOnce sync.Once
	file_proto_worker_proto_rawDescData []byte
)

func file_proto_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)))
	})
	return file_proto_worker_proto_rawDescData
}

var file_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_worker_proto_goTypes = []any{
	(*WorkerMessage)(nil),       // 0: worker.WorkerMessage
	(*Session)(nil),             // 1: worker.Session
	(*Heartbeat)(nil),           // 2: worker.Heartbeat
	(*RunLog)(nil),              // 3: worker.RunLog
	(*RunResult)(nil),           // 4: worker.RunResult
	(*OrchestratorMessage)(nil), // 5: worker.OrchestratorMessage
	(*SessionReady)(nil),        // 6: worker.SessionReady
	(*RunDispatch)(nil),         // 7: worker.RunDispatch
	(*RunAbort)(nil),            // 8: worker.RunAbort
}
var file_proto_worker_proto_depIdxs = []int32{
	1, // 0: worker.WorkerMessage.session:type_name -> worker.Session
	2, // 1: worker.WorkerMessage.heartbeat:type_name -> worker.Heartbeat
	3, // 2: worker.WorkerMessage.log:type_name -> worker.RunLog
	4, // 3: worker.WorkerMessage.result:type_name -> worker.RunResult
	6, // 4: worker.OrchestratorMessage.session:type_name -> worker.SessionReady
	7, // 5: worker.OrchestratorMessage.dispatch:type_name -> worker.RunDispatch
	8, // 6: worker.OrchestratorMessage.abort:type_name -> worker.RunAbort
	0, // 7: worker.WorkerService.Subscribe:input_type -> worker.WorkerMessage
	5, // 8: worker.WorkerService.Subscribe:output_type -> worker.OrchestratorMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_worker_proto_init() }
func file_proto_worker_proto_init() {
	if File_proto_worker_proto != nil {
		return
	}
	file_proto_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Session)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_Log)(nil),
		(*WorkerMessage_Result)(nil),
	}
	file_proto_worker_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_worker_proto_msgTypes[5].OneofWrappers = []any{
		(*OrchestratorMessage_Session)(nil),
		(*OrchestratorMessage_Dispatch)(nil),
		(*OrchestratorMessage_Abort)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_proto_rawDesc), len(file_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_proto_depIdxs,
		MessageInfos:      file_proto_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_proto = out.File
	file_proto_worker_proto_goTypes = nil
	file_proto_worker_proto_depIdxs = nil
}
